### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by exocode** [caius/homebrew-prince#4]
Hi there. I tried to install but it fails:

```

➜  ~ brew install prince
==> Installing prince from caius/prince
==> Downloading http://www.princexml.com/download/prince-11-macosx.tar.gz
######################################################################## 100.0%
Error: uninitialized constant #<Class:0x00000101050e68>::DATA
Did you mean?  Data
               Date
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/caius/homebrew-prince/Formula/prince.rb:15:in `patches'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1932:in `prepare_patches'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1095:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1923:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1922:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:119:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:12:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:92:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1900:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1093:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:108:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'
```

**Comment by giancarloguzopd** [comment]
Same thing is happening to me

**Comment by caius** [comment]
Huh, thanks for the report. I suspect homebrew has changed something in the way it loads the recipe and therefore my `DATA` trick doesn't work anymore

**Comment by caius** [comment]
Figured it out, looks like homebrew has changed from a `patches` method returning a string to having `patch …` declarations in the DSL.

Updated master in this repo, you should find prince installs ok now after running `brew update`. (If not, try a `brew uninstall caius/prince/prince` before installing again.)

Thanks for the reports, please feel free to reopen with new information if this is still an issue! 🎉
